export const icons = {
  email: require('../assets/icons/email.png'),
  eyeOpen: require('../assets/icons/eyeOpen.png'),
  eyeClose: require('../assets/icons/eyeClose.png'),
  emailLink: require('../assets/icons/emailLink.png'),
  closeIcon: require('../assets/icons/closeIcon.png'),
  searchLens: require('../assets/icons/searchLens.png'),
  filter: require('../assets/icons/filter.png'),
  cloudRefresh: require('../assets/icons/cloudRefresh.png'),
  bell: require('../assets/icons/bell.png'),
  bellPoint: require('../assets/icons/bellPoint.png'),
  user: require('../assets/icons/userMenu.png'),
  logout: require('../assets/icons/logout.png'),
  down: require('../assets/icons/down.png'),
  assignment: require('../assets/icons/assignment.png'),
  totalPatient: require('../assets/icons/totalPatient.png'),
  pendingAssignment: require('../assets/icons/pendingAssignment.png'),
  activePatient: require('../assets/icons/activePatient.png'),
  completeAssignment: require('../assets/icons/completeAssignment.png'),
  inactivePatient: require('../assets/icons/inactivePatient.png'),
};
