import { Dimensions, Platform, StatusBar, StyleSheet } from 'react-native';
import normalize from '../utils/normalize';
import { colors } from './colors';
import { fonts } from './fonts';

export const width = Dimensions.get('screen').width;
export const height = Dimensions.get('screen').height;

const wrapperWidth =
  width > 1300
    ? width - normalize(100)
    : width > 1200
      ? width - normalize(50)
      : width > 1000
        ? width - normalize(35)
        : width > 900
          ? width - normalize(30)
          : width < 900
            ? width - normalize(25)
            : width - normalize(16);

const css = StyleSheet.create({
  authWrapper: {
    width: wrapperWidth,
    alignSelf: 'center',
  },
  bgWhite: {
    backgroundColor: '#fff',
  },
  marginStatusBar: {
    marginTop: Platform.OS == 'android' ? StatusBar.currentHeight : null,
  },
  paddingStatusBar: {
    paddingTop: Platform.OS == 'android' ? StatusBar.currentHeight : null,
  },
  textLighte: {
    color: colors.ternaryTextColor
  },
  border:{
    borderWidth: 1,
    borderColor: colors.borderColor
  },
  cPrimary: {
    color: colors.primary
  },
  regular: {
    fontFamily: fonts.Regular,
  },
  medium: {
    fontFamily: fonts.Medium,
  },
  bold: {
    fontFamily: fonts.Bold
  },
  semiBold: {
    fontFamily: fonts.SemiBold
  },

  textPrimary: {
    color: colors.primaryTextColor
  },

  f1: { flex: 1 },
  fg1: { flexGrow: 1 },
  tac: { textAlign: 'center' },
  fw: { flexWrap: 'wrap' },
  ofh: { overflow: 'hidden' },
  bgRed: { backgroundColor: 'red' },
  bgYellow: { backgroundColor: 'yellow' },
  bgGreen: { backgroundColor: 'green' },
  asc: { alignSelf: 'center' },
  card: {
    borderRadius: 10,
    backgroundColor: '#fff',
    padding: normalize(10),
    overflow: 'hidden'
  },
  center: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  imgResponsive: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  // Margin Classes
  m0: { margin: 0 },
  m1: { margin: normalize(2) },
  m2: { margin: normalize(4) },
  m3: { margin: normalize(6) },
  m4: { margin: normalize(8) },
  m5: { margin: normalize(10) },
  m6: { margin: normalize(12) },
  m7: { margin: normalize(14) },
  m8: { margin: normalize(16) },
  m9: { margin: normalize(18) },
  m10: { margin: normalize(20) },
  m11: { margin: normalize(22) },
  m12: { margin: normalize(24) },
  m13: { margin: normalize(26) },
  m14: { margin: normalize(28) },
  m15: { margin: normalize(30) },
  m16: { margin: normalize(32) },
  m17: { margin: normalize(34) },
  m18: { margin: normalize(36) },
  m19: { margin: normalize(38) },
  m20: { margin: normalize(40) },

  // Horizontal Margin Classes
  mx0: { marginHorizontal: 0 },
  mx1: { marginHorizontal: normalize(2) },
  mx2: { marginHorizontal: normalize(4) },
  mx3: { marginHorizontal: normalize(6) },
  mx4: { marginHorizontal: normalize(8) },
  mx5: { marginHorizontal: normalize(10) },
  mx6: { marginHorizontal: normalize(12) },
  mx7: { marginHorizontal: normalize(14) },
  mx8: { marginHorizontal: normalize(16) },
  mx9: { marginHorizontal: normalize(18) },
  mx10: { marginHorizontal: normalize(20) },
  mx11: { marginHorizontal: normalize(22) },
  mx12: { marginHorizontal: normalize(24) },
  mx13: { marginHorizontal: normalize(26) },
  mx14: { marginHorizontal: normalize(28) },
  mx15: { marginHorizontal: normalize(30) },
  mx16: { marginHorizontal: normalize(32) },
  mx17: { marginHorizontal: normalize(34) },
  mx18: { marginHorizontal: normalize(36) },
  mx19: { marginHorizontal: normalize(38) },
  mx20: { marginHorizontal: normalize(40) },

  // Vertical Margin Classes
  my0: { marginVertical: 0 },
  my1: { marginVertical: normalize(2) },
  my2: { marginVertical: normalize(4) },
  my3: { marginVertical: normalize(6) },
  my4: { marginVertical: normalize(8) },
  my5: { marginVertical: normalize(10) },
  my6: { marginVertical: normalize(12) },
  my7: { marginVertical: normalize(14) },
  my8: { marginVertical: normalize(16) },
  my9: { marginVertical: normalize(18) },
  my10: { marginVertical: normalize(20) },
  my11: { marginVertical: normalize(22) },
  my12: { marginVertical: normalize(24) },
  my13: { marginVertical: normalize(26) },
  my14: { marginVertical: normalize(28) },
  my15: { marginVertical: normalize(30) },
  my16: { marginVertical: normalize(32) },
  my17: { marginVertical: normalize(34) },
  my18: { marginVertical: normalize(36) },
  my19: { marginVertical: normalize(38) },
  my20: { marginVertical: normalize(40) },

  // Left Margin Classes
  ml0: { marginLeft: 0 },
  ml1: { marginLeft: normalize(2) },
  ml2: { marginLeft: normalize(4) },
  ml3: { marginLeft: normalize(6) },
  ml4: { marginLeft: normalize(8) },
  ml5: { marginLeft: normalize(10) },
  ml6: { marginLeft: normalize(12) },
  ml7: { marginLeft: normalize(14) },
  ml8: { marginLeft: normalize(16) },
  ml9: { marginLeft: normalize(18) },
  ml10: { marginLeft: normalize(20) },
  ml11: { marginLeft: normalize(22) },
  ml12: { marginLeft: normalize(24) },
  ml13: { marginLeft: normalize(26) },
  ml14: { marginLeft: normalize(28) },
  ml15: { marginLeft: normalize(30) },
  ml16: { marginLeft: normalize(32) },
  ml17: { marginLeft: normalize(34) },
  ml18: { marginLeft: normalize(36) },
  ml19: { marginLeft: normalize(38) },
  ml20: { marginLeft: normalize(40) },
  ml21: { marginLeft: normalize(41) },

  ml22: { marginLeft: normalize(44) },

  // Right Margin Classes
  mr0: { marginRight: 0 },
  mr1: { marginRight: normalize(2) },
  mr2: { marginRight: normalize(4) },
  mr3: { marginRight: normalize(6) },
  mr4: { marginRight: normalize(8) },
  mr5: { marginRight: normalize(10) },
  mr6: { marginRight: normalize(12) },
  mr7: { marginRight: normalize(14) },
  mr8: { marginRight: normalize(16) },
  mr9: { marginRight: normalize(18) },
  mr10: { marginRight: normalize(20) },
  mr11: { marginRight: normalize(22) },
  mr12: { marginRight: normalize(24) },
  mr13: { marginRight: normalize(26) },
  mr14: { marginRight: normalize(28) },
  mr15: { marginRight: normalize(30) },
  mr16: { marginRight: normalize(32) },
  mr17: { marginRight: normalize(34) },
  mr18: { marginRight: normalize(36) },
  mr19: { marginRight: normalize(38) },
  mr20: { marginRight: normalize(40) },

  // Top Margin Classes
  mt0: { marginTop: 0 },
  mt1: { marginTop: normalize(2) },
  mt2: { marginTop: normalize(4) },
  mt3: { marginTop: normalize(6) },
  mt4: { marginTop: normalize(8) },
  mt5: { marginTop: normalize(10) },
  mt6: { marginTop: normalize(12) },
  mt7: { marginTop: normalize(14) },
  mt8: { marginTop: normalize(16) },
  mt9: { marginTop: normalize(18) },
  mt10: { marginTop: normalize(20) },
  mt11: { marginTop: normalize(22) },
  mt12: { marginTop: normalize(24) },
  mt13: { marginTop: normalize(26) },
  mt14: { marginTop: normalize(28) },
  mt15: { marginTop: normalize(30) },
  mt16: { marginTop: normalize(32) },
  mt17: { marginTop: normalize(34) },
  mt18: { marginTop: normalize(36) },
  mt19: { marginTop: normalize(38) },
  mt20: { marginTop: normalize(40) },

  // Bottom Margin Classes
  mb0: { marginBottom: 0 },
  mb1: { marginBottom: normalize(2) },
  mb2: { marginBottom: normalize(4) },
  mb3: { marginBottom: normalize(6) },
  mb4: { marginBottom: normalize(8) },
  mb5: { marginBottom: normalize(10) },
  mb6: { marginBottom: normalize(12) },
  mb7: { marginBottom: normalize(14) },
  mb8: { marginBottom: normalize(16) },
  mb9: { marginBottom: normalize(18) },
  mb10: { marginBottom: normalize(20) },
  mb11: { marginBottom: normalize(22) },
  mb12: { marginBottom: normalize(24) },
  mb13: { marginBottom: normalize(26) },
  mb14: { marginBottom: normalize(28) },
  mb15: { marginBottom: normalize(30) },
  mb16: { marginBottom: normalize(32) },
  mb17: { marginBottom: normalize(34) },
  mb18: { marginBottom: normalize(36) },
  mb19: { marginBottom: normalize(38) },
  mb20: { marginBottom: normalize(40) },

  // Padding Classes
  p0: { padding: 0 },
  p1: { padding: normalize(2) },
  p2: { padding: normalize(4) },
  p3: { padding: normalize(6) },
  p4: { padding: normalize(8) },
  p5: { padding: normalize(10) },
  p6: { padding: normalize(12) },
  p7: { padding: normalize(14) },
  p8: { padding: normalize(16) },
  p9: { padding: normalize(18) },
  p10: { padding: normalize(20) },
  p11: { padding: normalize(22) },
  p12: { padding: normalize(24) },
  p13: { padding: normalize(26) },
  p14: { padding: normalize(28) },
  p15: { padding: normalize(30) },
  p16: { padding: normalize(32) },
  p17: { padding: normalize(34) },
  p18: { padding: normalize(36) },
  p19: { padding: normalize(38) },
  p20: { padding: normalize(40) },

  // Bottom Padding Classes
  pb0: { paddingBottom: 0 },
  pb1: { paddingBottom: normalize(2) },
  pb2: { paddingBottom: normalize(4) },
  pb3: { paddingBottom: normalize(6) },
  pb4: { paddingBottom: normalize(8) },
  pb5: { paddingBottom: normalize(10) },
  pb6: { paddingBottom: normalize(12) },
  pb7: { paddingBottom: normalize(14) },
  pb8: { paddingBottom: normalize(16) },
  pb9: { paddingBottom: normalize(18) },
  pb10: { paddingBottom: normalize(20) },
  pb11: { paddingBottom: normalize(22) },
  pb12: { paddingBottom: normalize(24) },
  pb13: { paddingBottom: normalize(26) },
  pb14: { paddingBottom: normalize(28) },
  pb15: { paddingBottom: normalize(30) },
  pb16: { paddingBottom: normalize(32) },
  pb17: { paddingBottom: normalize(34) },
  pb18: { paddingBottom: normalize(36) },
  pb19: { paddingBottom: normalize(38) },
  pb20: { paddingBottom: normalize(40) },

  // Top Padding Classes
  pt0: { paddingTop: 0 },
  pt1: { paddingTop: normalize(2) },
  pt2: { paddingTop: normalize(4) },
  pt3: { paddingTop: normalize(6) },
  pt4: { paddingTop: normalize(8) },
  pt5: { paddingTop: normalize(10) },
  pt6: { paddingTop: normalize(12) },
  pt7: { paddingTop: normalize(14) },
  pt8: { paddingTop: normalize(16) },
  pt9: { paddingTop: normalize(18) },
  pt10: { paddingTop: normalize(20) },
  pt11: { paddingTop: normalize(22) },
  pt12: { paddingTop: normalize(24) },
  pt13: { paddingTop: normalize(26) },
  pt14: { paddingTop: normalize(28) },
  pt15: { paddingTop: normalize(30) },
  pt16: { paddingTop: normalize(32) },
  pt17: { paddingTop: normalize(34) },
  pt18: { paddingTop: normalize(36) },
  pt19: { paddingTop: normalize(38) },
  pt20: { paddingTop: normalize(40) },

  // Horizontal Padding Classes
  px0: { paddingHorizontal: 0 },
  px1: { paddingHorizontal: normalize(2) },
  px2: { paddingHorizontal: normalize(4) },
  px3: { paddingHorizontal: normalize(6) },
  px4: { paddingHorizontal: normalize(8) },
  px5: { paddingHorizontal: normalize(10) },
  px6: { paddingHorizontal: normalize(12) },
  px7: { paddingHorizontal: normalize(14) },
  px8: { paddingHorizontal: normalize(16) },
  px9: { paddingHorizontal: normalize(18) },
  px10: { paddingHorizontal: normalize(20) },
  px11: { paddingHorizontal: normalize(22) },
  px12: { paddingHorizontal: normalize(24) },
  px13: { paddingHorizontal: normalize(26) },
  px14: { paddingHorizontal: normalize(28) },
  px15: { paddingHorizontal: normalize(30) },
  px16: { paddingHorizontal: normalize(32) },
  px17: { paddingHorizontal: normalize(34) },
  px18: { paddingHorizontal: normalize(36) },
  px19: { paddingHorizontal: normalize(38) },
  px20: { paddingHorizontal: normalize(40) },

  // Vertical Padding Classes
  py0: { paddingVertical: 0 },
  py1: { paddingVertical: normalize(2) },
  py2: { paddingVertical: normalize(4) },
  py3: { paddingVertical: normalize(6) },
  py4: { paddingVertical: normalize(8) },
  py5: { paddingVertical: normalize(10) },
  py6: { paddingVertical: normalize(12) },
  py7: { paddingVertical: normalize(14) },
  py8: { paddingVertical: normalize(16) },
  py9: { paddingVertical: normalize(18) },
  py10: { paddingVertical: normalize(20) },
  py11: { paddingVertical: normalize(22) },
  py12: { paddingVertical: normalize(24) },
  py13: { paddingVertical: normalize(26) },
  py14: { paddingVertical: normalize(28) },
  py15: { paddingVertical: normalize(30) },
  py16: { paddingVertical: normalize(32) },
  py17: { paddingVertical: normalize(34) },
  py18: { paddingVertical: normalize(36) },
  py19: { paddingVertical: normalize(38) },
  py20: { paddingVertical: normalize(40) },

  // Left Padding Classes
  pl0: { paddingLeft: 0 },
  pl1: { paddingLeft: normalize(2) },
  pl2: { paddingLeft: normalize(4) },
  pl3: { paddingLeft: normalize(6) },
  pl4: { paddingLeft: normalize(8) },
  pl5: { paddingLeft: normalize(10) },
  pl6: { paddingLeft: normalize(12) },
  pl7: { paddingLeft: normalize(14) },
  pl8: { paddingLeft: normalize(16) },
  pl9: { paddingLeft: normalize(18) },
  pl10: { paddingLeft: normalize(20) },
  pl11: { paddingLeft: normalize(22) },
  pl12: { paddingLeft: normalize(24) },
  pl13: { paddingLeft: normalize(26) },
  pl14: { paddingLeft: normalize(28) },
  pl15: { paddingLeft: normalize(30) },
  pl16: { paddingLeft: normalize(32) },
  pl17: { paddingLeft: normalize(34) },
  pl18: { paddingLeft: normalize(36) },
  pl19: { paddingLeft: normalize(38) },
  pl20: { paddingLeft: normalize(40) },

  // Right Padding Classes
  pr0: { paddingRight: 0 },
  pr1: { paddingRight: normalize(2) },
  pr2: { paddingRight: normalize(4) },
  pr3: { paddingRight: normalize(6) },
  pr4: { paddingRight: normalize(8) },
  pr5: { paddingRight: normalize(10) },
  pr6: { paddingRight: normalize(12) },
  pr7: { paddingRight: normalize(14) },
  pr8: { paddingRight: normalize(16) },
  pr9: { paddingRight: normalize(18) },
  pr10: { paddingRight: normalize(20) },
  pr11: { paddingRight: normalize(22) },
  pr12: { paddingRight: normalize(24) },
  pr13: { paddingRight: normalize(26) },
  pr14: { paddingRight: normalize(28) },
  pr15: { paddingRight: normalize(30) },
  pr16: { paddingRight: normalize(32) },
  pr17: { paddingRight: normalize(34) },
  pr18: { paddingRight: normalize(36) },
  pr19: { paddingRight: normalize(38) },
  pr20: { paddingRight: normalize(40) },

  fs11: { fontSize: 11 },
  fs12: { fontSize: 12 },
  fs13: { fontSize: 13 },
  fs14: { fontSize: 14 },
  fs15: { fontSize: 15 },
  fs16: { fontSize: 16 },
  fs17: { fontSize: 17 },
  fs18: { fontSize: 18 },
  fs19: { fontSize: 19 },
  fs20: { fontSize: 20 },
  fs21: { fontSize: 21 },
  fs22: { fontSize: 22 },
  fs23: { fontSize: 23 },
  fs24: { fontSize: 24 },
  fs25: { fontSize: 25 },
  fs26: { fontSize: 26 },
  fs27: { fontSize: 27 },
  fs28: { fontSize: 28 },
  fs29: { fontSize: 29 },
  fs30: { fontSize: 30 },
  fs31: { fontSize: 31 },
  fs32: { fontSize: 32 },
  fs33: { fontSize: 33 },
  fs34: { fontSize: 34 },
  fs35: { fontSize: 35 },
  fs36: { fontSize: 36 },
  fs37: { fontSize: 37 },
  fs38: { fontSize: 38 },
  fs39: { fontSize: 39 },
  fs40: { fontSize: 40 },
  fs41: { fontSize: 41 },
  fs42: { fontSize: 42 },
  fs43: { fontSize: 43 },
  fs44: { fontSize: 44 },
  fs45: { fontSize: 45 },
  fs46: { fontSize: 46 },
  fs47: { fontSize: 47 },
  fs48: { fontSize: 48 },
  fs49: { fontSize: 49 },
  fs50: { fontSize: 50 },

  w10: { width: '10%' },
  w20: { width: '20%' },
  w30: { width: '30%' },
  w33: { width: '33%' },
  w40: { width: '40%' },
  w50: { width: '50%' },
  w60: { width: '60%' },
  w70: { width: '70%' },
  w80: { width: '80%' },
  w90: { width: '90%' },
  w100: { width: '100%' },
  mw33: { minWidth: '33%' },
  mw40: { minWidth: '40%' },
  mw50: { minWidth: '50%' },

  //align-items

  aic: { alignItems: 'center' },
  aife: { alignItems: 'flex-end' },
  aifs: { alignContent: 'flex-start' },
  jcc: { justifyContent: 'center' },
  jcsb: { justifyContent: 'space-between' },
  fdr: { flexDirection: 'row' },

  headerTxt: {
    fontFamily: fonts.Medium,
    fontSize: normalize(18),
    color: colors.primaryTextColor,
  },
  subHeaderTxt: {
    fontFamily: fonts.Regular,
    fontSize: normalize(9),
    color: colors.secondaryTextColor,
  },

  row: {
    flexDirection: 'row',
  },
  rowBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  inputIconStyle: {
    height: normalize(20),
    width: normalize(20),
    resizeMode: 'contain',
    tintColor: '#939598',
    opacity: 0.5,
  },

  bgColor: {
    backgroundColor: colors.bgColor,
  },
  closeIconWrapStyle:{
    width: 50,
    height: 50,
    position: 'absolute',
    top: -25,
    right: -25,
  },
  closeIconStyle:{
    width: 50,
    height: 50,
    resizeMode: 'contain',
  },
});
export default css;
